# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine
GAMEPROJECTFILE =/home/dmitry/Documents/UnrealProjects/Stalker/Stalker.uproject

TARGETS = \
	Stalker-Linux-DebugGame  \
	Stalker-Linux-Shipping  \
	Stalker \
	StalkerEditor-Linux-DebugGame  \
	StalkerEditor-Linux-Shipping  \
	StalkerEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend StalkerEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug StalkerEditor-Linux-Debug


Stalker-Linux-DebugGame:
	 $(PROJECTBUILD) Stalker Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Stalker-Linux-Shipping:
	 $(PROJECTBUILD) Stalker Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Stalker:
	 $(PROJECTBUILD) Stalker Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

StalkerEditor-Linux-DebugGame:
	 $(PROJECTBUILD) StalkerEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

StalkerEditor-Linux-Shipping:
	 $(PROJECTBUILD) StalkerEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

StalkerEditor:
	 $(PROJECTBUILD) StalkerEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
